# Generated by Django 4.2.4 on 2024-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microlensing_targets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microlensingtarget",
            name="latest_data_utc",
            field=models.DateTimeField(null=True),
        ),
    ]
