# Generated by Django 4.2.4 on 2024-05-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microlensing_targets", "0002_alter_microlensingtarget_latest_data_utc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microlensingtarget",
            name="observing_mode",
            field=models.CharField(default=" No", max_length=20),
        ),
    ]
