# Generated by Django 4.2.4 on 2024-06-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microlensing_targets", "0003_alter_microlensingtarget_observing_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microlensingtarget",
            name="fit_covariance",
            field=models.JSONField(default=dict),
        ),
    ]
