# Generated by Django 4.2.4 on 2024-06-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microlensing_targets", "0004_alter_microlensingtarget_fit_covariance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microlensingtarget",
            name="observing_mode",
            field=models.CharField(default=" No", max_length=30),
        ),
    ]
