# Generated by Django 4.2.4 on 2024-07-12 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microlensing_targets", "0005_alter_microlensingtarget_observing_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="microlensingtarget",
            name="gaia_source_id",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="microlensingtarget",
            name="interferometry_mode",
            field=models.CharField(blank=True, default="", max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="microlensingtarget",
            name="mag_now_passband",
            field=models.CharField(blank=True, default="", max_length=10, null=True),
        ),
    ]
