# Generated by Django 4.2.4 on 2024-07-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "microlensing_targets",
            "0006_alter_microlensingtarget_gaia_source_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="microlensingtarget",
            name="fit_covariance",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="microlensingtarget",
            name="latest_data_utc",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
