{{- if .Values.gaiaclassifier.enabled -}}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "mop.fullname" . }}-gaiaclassifier
  labels:
{{ include "mop.labels" . | indent 4 }}
    app.kubernetes.io/component: "gaiaclassifier"
spec:
  concurrencyPolicy: "Forbid"
  failedJobsHistoryLimit: {{ default 1 .Values.gaiaclassifier.failedJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ default 3 .Values.gaiaclassifier.successfulJobsHistoryLimit }}
  startingDeadlineSeconds: 120
  schedule: "{{ .Values.gaiaclassifier.schedule }}"
  jobTemplate:
    metadata:
      labels:
        {{- include "mop.labels" . | nindent 8 }}
        app.kubernetes.io/component: "gaiaclassifier"
    spec:
      activeDeadlineSeconds: 10800
      template:
        metadata:
          labels:
            {{- include "mop.labels" . | nindent 12 }}
            app.kubernetes.io/component: "gaiaclassifier"
        spec:
          restartPolicy: Never
          containers:
            - name: {{ .Chart.Name }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              command:
                - python
                - manage.py
                - gaia_classifier
              args: ["all"]
              env:
                {{- include "mop.backendEnv" . | nindent 16 }}
              resources:
                {{- toYaml .Values.gaiaclassifier.resources | nindent 16 }}
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
                  readOnly: false

          volumes:
            - name: tmp
              emptyDir:
                medium: Memory
                sizeLimit: 16Mi


            {{- with .Values.nodeSelector }}
              nodeSelector:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.affinity }}
              affinity:
                {{- toYaml . | nindent 16 }}
            {{- end }}
            {{- with .Values.tolerations }}
              tolerations:
                {{- toYaml . | nindent 16 }}
            {{- end }}

{{- end }}
