name: "Continuous Deployment"
on:
  push:
    branches:
      - master
  release:
    types:
      - published

jobs:
  cd:
    uses: LCOGT/reusable-workflows/.github/workflows/continuous-deployment.yaml@main
    with:
      skaffoldBuildModules: "mop"
    secrets: inherit
